# frozen_string_literal: true

source "https://rubygems.org"
# gemspec

# use local theme gem for testing
gem "jekyll-theme-quarkyll", path: "../"

# If you have any plugins, put them here!
group :jekyll_plugins do
  # gem 'jekyll-algolia', '~> 1.0'
end

gem "wdm", "~> 0.1.0" if Gem.win_platform?
