# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://drupix.github.io/jekyll-theme-quarkyll/docs/quick-start-guide/#installing-the-theme


# Available Theme options:
    # header-fixed        : When enabled, the header will be fixed at the top of the browser
    # header-animated     : When enabled, the header will animate to a smaller header when scrolling
    # header-dark         : When enabled, a dark-friendly style will be used
    # header-transparent  : When enabled, a transparent style will be used
    # sticky-footer       : When enabled, the footer will be sticky at the bottom of the browser
    # footer-dark         : When enabled, a dark-friendly style will be used
# For easier integration add options in one string. Options are added in the body class
theme_options: "header-fixed header-animated header-dark sticky-footer footer-dark"

# Grid size: grid-sm, grid-md grid-lg
grid-size       : grid-lg

# Other config
# encoding        : "utf-8"
locale          : "fr-CH"
title           : "Quarkyll Theme"
title_separator : "-"
slogan          : "A simple Jekyll Theme"
description     : "An amazing website."
logo            : "/assets/images/logo-quarkyll.png" # path of logo image to display in the header, e.g. "/assets/images/logo.png"
favicon         : # path of favicon image to display in browser tab, e.g. "/assets/images/favicon.ico"

# SEO Related
# google_site_verification :
# bing_site_verification   :
# yandex_site_verification :

# Analytics
# analytics:
#   provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
#   google:
#     tracking_id          :
#     anonymize_ip         : # true, false (default)

# Collections
collections:
  help_pages:
    output: true
    label: help_page
    permalink: /help-pages/:path/