# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://drupix.github.io/jekyll-theme-quarkyll/docs/quick-start-guide/#installing-the-theme


# Theme options: header-fixed header-animated header-dark sticky-footer footer-dark
theme_options: "header-fixed header-animated header-dark sticky-footer footer-dark"

# Grid size: grid-sm, grid-md grid-lg
grid-size : grid-lg
title     : "Quarkyll Theme"
slogan    : "A simple Jekyll Theme"
logo      : "/assets/images/logo-quarkyll.png" # path of logo image to display in the header, e.g. "/assets/images/logo.png"
favicon   : # path of favicon image to display in browser tab, e.g. "/assets/images/favicon.ico"

# SEO Related
# google_site_verification :
# bing_site_verification   :
# yandex_site_verification :

# Analytics
# analytics:
#   provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
#   google:
#     tracking_id          :
#     anonymize_ip         : # true, false (default)

# Collections
collections:
  help_pages:
    output: true
    label: help_page
    permalink: /help-pages/:path/