# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://drupix.github.io/jekyll-theme-quarkyll/docs/quick-start-guide/#installing-the-theme

# Theme options: (added as body class)
theme_options: [
  header-fixed,        # When enabled, the header will be fixed at the top of the browser
  header-animated,     # When enabled, the header will animate to a smaller header when scrolling
  header-dark,         # When enabled, a dark-friendly style will be used
  header-transparent,  # When enabled, a transparent style will be used
  sticky-footer,       # When enabled, the footer will be sticky at the bottom of the browser
  footer-dark,         # When enabled, a dark-friendly style will be used
]

# Grid size: grid-sm, grid-md grid-lg
grid-size       : grid-lg

# Other config
# encoding        : "utf-8"
locale          : "fr-CH"
title           : "Quarkyll Theme"
title_separator : "-"
slogan          : "A simple Jekyll Theme"
description     : "An amazing website."
favicon         : # path of favicon image to display in browser tab, e.g. "/assets/images/favicon.ico"
# Logo functionality:
  # If logo_light is defined, logo will automatically switch between
  # logo and logo_light depending on theme_options[header-dark] and/or
  # theme_options[header-transparent] if defined.
  # This allow for example to automatically switch between the logo and her lighter version
  #
  # Note that both logo and logo_light are otionals but if you want to display a logo
  # you must define the logo variable
logo       : "/assets/images/logo-quarkyll-light.png"       # path of logo image to display in the header, e.g. "/assets/images/logo.png"
logo_light : "/assets/images/logo-quarkyll-light.png" # path of alternate logo image to display in the header, e.g. "/assets/images/logo.png"

# email: your-email@example.com
# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

url         : # the base hostname & protocol for your site e.g. "https://drupix.github.io"
baseurl     : # the subpath of your site, e.g. "/blog"
repository  :

plugins:
  - jekyll-menus

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-menus
  # - jekyll-paginate
  # - jekyll-sitemap
  # - jekyll-gist
  # - jekyll-feed
  # - jemoji
  # - jekyll-include-cache

# SEO Related
# google_site_verification :
# bing_site_verification   :
# yandex_site_verification :

# Analytics
# analytics:
#   provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
#   google:
#     tracking_id          :
#     anonymize_ip         : # true, false (default)

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
include:
  - .htaccess
  - _pages
exclude:
  - "*.vscode"
  # - vendor
  - .asset-cache
  - .bundle
  # - .jekyll-assets-cache
  # - .jekyll-cache/
  - .sass-cache/
  # - assets/js/plugins
  # - assets/js/vendor
  # - assets/js/site.js
  # - assets/js/quarkyll-bootstrap.js
  - CHANGELOG
  - config
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules/
  - README
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - /docs # ignore Quarkyll /docs
  - /test # ignore Quarkyll /test

# Collections
collections:
  help_pages:
    output: true
    label: help_page
    permalink: /:collection/:path/
  devel_pages:
    output: true
    label: devel_page
    permalink: /:collection/:path/
